### ISSUE TITLE
SetTimeout should take a time.Duration as argument

### ISSUE THREAD

**Issue by erikdubbelboer** [alessiosavi/Requests#3]
Why is this function so complicated? https://github.com/alessiosavi/Requests/blob/ccb647f13fdb72323f425c226fb5651ce80c0f7d/Requests.go#L59-L97

Why can't it either take a `time.Duration` as argument. Or otherwise a string that you then parse with [`time.ParseDuration`](https://golang.org/pkg/time/#ParseDuration)?

**Comment by alessiosavi** [comment]
Hi @erikdubbelboer, thank you for point it out.
You are right, is no necessary to reinvent the wheel.
From the usability POV, in your opinion, is better to accept a `time.Duration` or parsing a string using `time.ParseDuration`?

**Comment by erikdubbelboer** [comment]
I would always take a `time.Duration` as input.

**Comment by alessiosavi** [comment]
Fix in 100e65fc33105c897c527ac8e66f8e592efa6c2d.

Please, feel free to modify.
