### ISSUE TITLE
Escape the `GET` request

### ISSUE THREAD

**Issue by alessiosavi** [alessiosavi/Requests#4]
**Is your feature request related to a problem? Please describe.**
During the `GET` request, the parameters have to be escaped

**Describe the solution you'd like**
During the request initialization (`InitRequest` method), the method `url.PathEscape` have to be used to format the string after the first occurrence of the character `/`

**Comment by franszhafran** [comment]
Hello, thanks for opened an issue

I would like to solve this issue please

With current code:
url = https://example.com/user?name=@berbatov
**What I will do:**
url = https://example.com/user?name=%24berbatov

I consider this will solve the problem, what do you think about it?

**Comment by alessiosavi** [comment]
Hi @franszhafran, thank you for the interest in the repo.

Of course, i think that one possible solution is the following one:
1) The procedure have to be written in the `InitRequest` method.
2) Search the first occurrence of character `/`
3) Apply `url.PathEscape` method to the remaining part of string
4) Concatenate the first part of the string with the new one
5) Set the URL

**Comment by franszhafran** [comment]
Ok understood, I will do it and notify you here when I've done, also I will create a PR just as usual

**Comment by franszhafran** [comment]
Hi @alessiosavi , please check PR that I've made https://github.com/alessiosavi/Requests/pull/6

**Comment by alessiosavi** [comment]
Hi @franszhafran, thank you for the effort!

I've merged the pull request and add a test case in #7
